name = "QuantumComputing"
uuid = "d9b293fb-c9d6-4f28-90fc-3c1ac1ab7f56"
authors = ["Dhruva Sambrani <44899822+DhruvaSambrani@users.noreply.github.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
